### ISSUE TITLE
Add hold functionality for incoming and outgoing calls

### ISSUE THREAD

**Issue by 9mido** [twilio/twilio-voice.js#32]
Hold functionality is not part of the javascript SDK.

Mute functionality helps in certain situations, but it leaves the other party wondering if you are still on the line. If you leave the other party on mute too long, they will think you hung up on them and they will most likely hang up on you if they don't hear anything.

Adding hold music to let the other party know you are still on the line with them is useful when you have to be away from the phone for longer periods of time.

Another scenario would be to put a current call on hold and then accept another incoming call that comes in at the same time as the current call is in progress.

**Comment by ryan-rowland** [comment]
Hi @9mido, thanks for bringing this up. Hold functionality is a hot topic internally and something we've been looking at implementing for a while now. This is something that should be done server-side ideally, so it's likely not something we will implement SDK-side. Currently, this can be done by using Conference objects rather than Call objects, however, we are working internally on making this easier both on the server side and from the SDK side.

**Comment by karan-bacancy** [comment]
Is there any update on this ?

**Comment by charliesantos** [comment]
Hi @karan-bacancy , thanks for the ping. We don't have any updates on this. As Ryan mentioned, you should be able to do this on the server side.

**Comment by karan-bacancy** [comment]
Can you please let me know how we can implement hold feature on server side.. because i have tried to create conference using server side api but not able to create conference in regular call.. can you please guide me on this.? or if you have any demo then please provide us. so we can sorted out both feature hold & conference

**Comment by charliesantos** [comment]
Hi @karan-bacancy , sure thing!
You will need to use conference by default, not regular calls. Then you can update a participant resource and set the hold property to true. See https://www.twilio.com/docs/voice/api/conference-participant-resource#update-a-participant-resource
Also, please see this page for more info https://www.twilio.com/docs/voice/conference

**Comment by suraj-mloflo** [comment]
Sory Sir but many functionilty affeted for this way is there any solution for this

**Comment by suraj-mloflo** [comment]
Hi  @karan-bacancy  i already find a solution for the hold in regular calls,

**Comment by karan-bacancy** [comment]
@suraj-mloflo Can you please share your code stuff and info how you had implemented in your project it will really helpfull for me..
Thanks in advance

**Comment by suraj-mloflo** [comment]
In hold, we are redirecting a live call to a conference, and it is working perfectly.  refrence : [https://stackoverflow.com/questions/22643800/twilio-how-to-move-an-existing-call-to-a-conference](url) and then you can hold easily
But in this also have problem at call ending before call confrencing. that you can easily handle in server side

**Comment by charliesantos** [comment]
Closing this now. Please feel free to follow up if you have any further questions.
