### ISSUE TITLE
does it support react native?

### ISSUE THREAD

**Issue by thanhnvpk01168** [twilio/twilio-voice.js#45]
Can you tell me if I use this lib and use it for react native, will it work properly?
Hope you can help me, thank you in advance

**Comment by mdovn** [comment]
> Can you tell me if I use this lib and use it for react native, will it work properly? Hope you can help me, thank you in advance

I believe not, however, you can take a look at https://github.com/MrHertal/react-native-twilio-phone

**Comment by ryan-rowland** [comment]
Hi @thanhnvpk01168,
This SDK could be used inside a React Native application, however, it does not provide the full React Native wrapper. In order to do so, a React Native application would need to define a common API that can reach into the JS, iOS and Android SDKs to make functionality cross-platform.

There are currently a few third-party React Native approaches out there that do this. An official React Native SDK for Voice has been discussed internally but I'm unable to provide any details on that at this point in time.

**Comment by dwbelliston** [comment]
Looking forward to this!

https://github.com/twilio/twilio-voice-react-native
