### ISSUE TITLE
[BUG] CHANGELOG v2.1.0 Confusion

### ISSUE THREAD

**Issue by gwing33** [twilio/twilio-voice.js#58]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
While the CHANGELOG says 2.1.0 exists, it is not yet released. I see it is in a `2.1.0-rc5` state, and that doesn't seem to be pushed up to npm either.

```bash
$ npm i @twilio/voice-sdk@latest --save
```

**Expected behavior:**

I would expect CHANGELOG would properly specify the correct version. In this case `2.1.0-rc5` since `2.1.0` does not exist on NPM.

**Actual behavior:**
The latest is currently `2.0.1` not `2.1.0`.

**Comment by ryan-rowland** [comment]
Hi @gwing33, it seems like this issue was opened when the publicly available version was 2.0.1, and while the master reflected our 2.1 branch which was currently in development. I apologize if there was any confusion, but our primary branch is our dev branch so you may see a newer version here when compared to what is available on npm.

You should now see 2.1.0 available on NPM as it has been officially released. Please keep in mind that you should not link directly to our master branch in production, as development is happening frequently and therefore is not guaranteed to be bug-free. I'd recommend only using the latest version available on NPM.
