### ISSUE TITLE
[BUG] Cancel Event Not Triggered When Ignoring Call

### ISSUE THREAD

**Issue by JAD3N** [twilio/twilio-voice.js#92]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

When receiving an incoming call, using a button I call the `ignore` method on the call. I am expecting the cancel event to be emitted as a result of that.

This is mentioned on this page here:
https://www.twilio.com/docs/voice/sdks/javascript/twiliocall#cancel-event

**Actual behavior:**

No event is triggered but the call is ignored successfully.

**Software versions:**

 - [x] Browser(s): Firefox
 - [x] Operating System: Manjaro + Gnome
 - [x] twilio.js: 2.1.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by bld010** [comment]
Can you share the code you're using to produce this behavior (specifically where you're adding the "cancel" event listener for the incoming call, and where you're invoking call.ignore)?

**Comment by JAD3N** [comment]
I'm adding the event listener to the incoming call immediately after receiving it via the incoming event. I'm using the events to listen for status changes:

```js
const events = [
	'accept',
	'cancel',
	'disconnect',
	'error',
	'mute',
	'reconnected',
	'reconnecting',
	'reject',
	'ignore',
];

let prevStatus = call.status();
for (const event of events) {
	call.on(event, () => {
		const status = call.status();
		if (prevStatus !== status) {
			prevStatus = status;
			win.postMessage({ type: 'status', status });
		}
	});
}
```

The `ignore` method is called based on a button click in another window and communicated via postMessage, which is always after the event listeners are registered.

**Comment by mhuynh5757** [comment]
Hi all, thanks for bringing this issue up, we've created a ticket to track this one internally.

**Comment by aehrenthal** [comment]
I am facing the same issue. When calling
```
call.ignore();
```

the **cancel** event listener does not get triggered. I am registering it in the following manner:
```
call.on('cancel', onCallCancel);
```
I can confirm that all other event listeners are properly working, e.g. calling
```
call.disconnect()
```
is triggering the **cancel** event listener. As per the Twilio Voice SDK documentation, the cancel event listener should be called when either

> 1. Invoking call.ignore() on an incoming call.
> 2. Invoking call.disconnect() on an outgoing call before the recipient answered.

As per the description above, #2 gets properly invoked while #1 does not. Happy to provide a more elaborate example in case it helps 😊

**Comment by thexeos** [comment]
In our case, it is the opposite. Number 1 from that list - `Invoking call.disconnect() on an outgoing call before the recipient answered.` - does not trigger `cancel`.

We are using `v2.5.0` and we end the call when the dialing tones are coming through the user's speakers by calling `device.disconnectAll()`.

**Comment by gruckion** [comment]
Hi @JAD3N,

Please see the following page.

https://www.twilio.com/docs/voice/sdks/javascript/migrating-to-js-voice-sdk-20#cancel-event-no-longer-emitted-by-call-instance-in-response-to-a-local-callignore


> # ['cancel' event no longer emitted by Call instance in response to a local call.ignore()](https://www.twilio.com/docs/voice/sdks/javascript/migrating-to-js-voice-sdk-20#cancel-event-no-longer-emitted-by-call-instance-in-response-to-a-local-callignore)
> The Call instance no longer emits the 'cancel' event in response to a local call.ignore(). Instead, it will only fire when the remote end has canceled.

As you can see this is not the expected behaviour. 

1. Customer dials in
2. Agent triggers `call.ignore()` via the UI
3. Expected `cancel` event is NOT called

I am currently facing an issue where if the customer who is calling in hangs up on their end then the `cancel` event is NOT called.

So for me the `cancel` event is NEVER triggered.

If I dial out and then hang up from my phone I hear the hang up sound effect but no events are triggered.

If I dial in `incoming` is triggered, but if I hangup it does NOT trigger `cancel` if I answer then the user hangs up it does not trigger `cancel`.

**Comment by gruckion** [comment]
@JAD3N 

https://www.twilio.com/docs/voice/sdks/javascript/migrating-to-js-voice-sdk-20#cancel-event-no-longer-emitted-by-call-instance-in-response-to-a-local-callignore

It mentions here that they no longer do this by design.

**Comment by JAD3N** [comment]
@gruckion

Nice find, then some of docs must be out-of-date then for the JavaScript SDK.

Since this appears to be intentional, should I raise a separate issue (feature request) for perhaps adding an `ignore` event for whenever a call is ignored?

**Comment by ibnsultan** [comment]
It's been almost a year since this issue was raised, and I'm wondering if there have been any updates. The documentation still indicates that the cancel event is triggered when the end-user ignores a call.

@JAD3N @gruckion, have you found any alternatives or workarounds for this? Any insights would be greatly appreciated!

**Comment by JAD3N** [comment]
@ibnsultan I believe I used was to manually polled (setInterval) the call object to check it's status and then triggered an emit event on the call so my normal `.on("ignore", ...)` event listeners would work.

**Comment by charliesantos** [comment]
As mentioned by @gruckion [here](https://github.com/twilio/twilio-voice.js/issues/92#issuecomment-1723172148), we no longer do this by design.

Thank you everyone for your feedback. We will update our docs accordingly. If you need this feature, please use your twilio account to submit a feature request ticket.
